### ISSUE TITLE
[DEV]: Rework Server Permissions

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/Chatter#1]
# About
I have seen some people asking about permissions.  
So there is room to improve the system.
# Tasks
- [ ] Make a config file to handle editor permissions.
- [ ] Permissions enable/disable players the ability to use the editor for specific elements.
- [ ] Per role permission **[Admin, Moderator, Player]**
- [ ] Remove the old game rule system.
