### ISSUE TITLE
[DEV]: Rework command system

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/Chatter#2]
# About
The command system will need to be worked on to make it work with the new permission system.
# Tasks
- [ ] Add support for the new config permission system.
- [ ] Remove support for the old game rule permission system.
- [ ] Add support for editing other player settings based on the "others" permission settings in each role's permissions.
- [ ] Optimize the procedures if possible.
